apiVersion: apps/v1
kind: Deployment
metadata:
  name: idealista-property-scraper
  namespace: real-state-fizgon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idealista-property-scraper
  template:
    metadata:
      labels:
        app: idealista-property-scraper
    spec:
      hostname: idealista-property-scraper
      securityContext:
        runAsUser: 1
        runAsGroup: 1
        fsGroup: 1001
        runAsNonRoot: false
      containers:
      - name: idealista-property-scraper
        image: idealista-property-scraper:local
        imagePullPolicy: Never
        securityContext:
          privileged: true
        ports:
        - name: vnc-tcp
          containerPort: 5900
          protocol: TCP
        volumeMounts:
        - name: app-secrets
          mountPath: /app/secrets.json
          subPath: secrets.json
          readOnly: true
        - name: images-persistent
          mountPath: /app/output/images
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: false
      volumes:
      - name: app-secrets
        secret:
          secretName: idealista-property-secrets
          items:
          - key: secrets.json
            path: secrets.json
      - name: images-persistent
        persistentVolumeClaim:
          claimName: idealista-property-images-pvc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: idealista-property-scraper-vnc
  namespace: real-state-fizgon
spec:
  selector:
    app: idealista-property-scraper
  ports:
  - name: vnc-tcp
    port: 5900
    targetPort: 5900
    protocol: TCP
